### ISSUE TITLE
Markdown not rendering - something to do with Tailwind css?

### ISSUE THREAD

**Issue by phhu** [tomreinert/minimal-11ty-tailwind-starter#4]
Hello,

I cloned this, having liked the presentation. I tried adding some markdown text in one of the blog posts, and found that standard markdown elements ( "#" headings, "*" lists etc) do not render with expected styling (so no bullet points, and headers the same size and font as other text).

I'm not sure why this happens, as the HTML elements are present.  I'm guessing it's something to do with tailwind CSS, which I don't understand. If I disable "@tailwind components" in the main.css file, then I do get the rendering, at the expense of the rest of the style.

What should I do to get markdown to render as expected? (having a good correspondence between the markdown text and the final appearance is the obvious attraction of markdown: I don't necessarily want to have to learn tailwind in detail to have this)

**Comment by sarthakgupta072** [comment]
Hi @phhu Did you find any solution to this? I am struggling with the same issue in a different project.

**Comment by tomreinert** [comment]
@phhu @sarthakgupta072 

This is because tailwind resets all font sizes and styling. 

You can either define the styles yourself in main.css - for example

```
h1{
@apply text-xl
}
```

Or – probably this is easier – use the tailwind typography plugin
https://github.com/tailwindlabs/tailwindcss-typography
